version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm whoami
      - run: npm run semantic-release || true
