version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm whoami
      - run: npm t
      - run: npm run semantic-release || true

workflows:
  version: 2
  build:
    jobs:
      - tests:
          context: org-npm-credentials